"""Domain models for the Product Discovery Agent System.

The project intentionally uses stdlib dataclasses instead of heavyweight ML
frameworks so the demo can run anywhere. The architecture is designed so each
agent can later be backed by a real LLM call, retrieval index, vector database,
or multimodal model.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass, field
from typing import Any


@dataclass
class ProductBrief:
    """The high-level user request and constraints."""

    company: str
    product: str
    target_user: str
    goal: str
    constraints: list[str] = field(default_factory=list)
    strategic_themes: list[str] = field(default_factory=list)


@dataclass
class EvidenceItem:
    """A piece of customer/product evidence used for grounded ideation."""

    id: str
    source: str
    text: str
    user_segment: str = "unknown"
    severity: int = 3  # 1 low, 5 high
    tags: list[str] = field(default_factory=list)


@dataclass
class Insight:
    """A clustered pain point or opportunity inferred from evidence."""

    id: str
    title: str
    summary: str
    evidence_ids: list[str]
    confidence: float
    tags: list[str] = field(default_factory=list)


@dataclass
class ProductDirection:
    """A candidate product direction generated by the ideation agents."""

    id: str
    title: str
    one_liner: str
    target_user: str
    core_loop: str
    why_now: str
    evidence_ids: list[str]
    differentiator: str
    implementation_notes: list[str]
    risks: list[str]
    canvas_column: str = "Ideas"
    canvas_row: int = 0


@dataclass
class CritiqueScore:
    """Structured review of a candidate product direction."""

    direction_id: str
    customer_alignment: int
    novelty: int
    feasibility: int
    strategic_fit: int
    clarity: int
    risk_level: int
    summary: str
    recommended_next_step: str

    @property
    def weighted_score(self) -> float:
        """Weighted score that penalizes risk."""
        return round(
            0.25 * self.customer_alignment
            + 0.20 * self.novelty
            + 0.20 * self.feasibility
            + 0.20 * self.strategic_fit
            + 0.15 * self.clarity
            - 0.10 * self.risk_level,
            2,
        )


@dataclass
class CanvasCard:
    """Visual canvas representation for one product direction."""

    id: str
    title: str
    column: str
    row: int
    body: str
    evidence: list[str]
    score: float
    tags: list[str] = field(default_factory=list)


@dataclass
class CodingSpec:
    """Coding-agent-ready product handoff."""

    direction_id: str
    feature_name: str
    user_story: str
    functional_requirements: list[str]
    non_functional_requirements: list[str]
    data_contract: dict[str, Any]
    acceptance_criteria: list[str]
    analytics_events: list[str]
    open_questions: list[str]


@dataclass
class EvalResult:
    """Evaluation output for the whole agent pipeline."""

    metric: str
    score: float
    explanation: str


@dataclass
class AgentRun:
    """End-to-end run artifact. This is the object persisted to JSON."""

    brief: ProductBrief
    evidence: list[EvidenceItem]
    insights: list[Insight]
    directions: list[ProductDirection]
    critiques: list[CritiqueScore]
    canvas_cards: list[CanvasCard]
    selected_direction_id: str | None
    coding_spec: CodingSpec | None
    evals: list[EvalResult]
    decision_log: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)
